### ISSUE TITLE
[W 0:12:14:839] The /amigo/ed/navigation/cloud observation buffer has not been updated for 56.64 seconds, and it should be updated every 1.00 seconds.

### ISSUE THREAD

**Issue by Timple** [tue-robotics/cb_base_navigation#10]
Lots of errors

**Comment by reinzor** [comment]
Check: rgbd_to_ros should also publish a pointcloud and the costmaps shoud subscribe to the correct topics

**Comment by MatthijsBurgh** [comment]
The plugin subscribes to the rgbd topic, so not related to rgbd_to_ros. Futhermore not a current issues.
