### ISSUE TITLE
Global planner couldn't plan a path to the specified constraints

### ISSUE THREAD

**Issue by Rayman** [tue-robotics/cb_base_navigation#6]
Grasp goals from the GUI generate constrains that cannot be satisfied by the global planner. The following message will be printed.
```
Global planner couldn't plan a path to the specified constraints. Are the constraints you specified valid?
```
One of the latest commits (d8638a957b2276a2262f6110eab4d3ecdeccba77, b15fc1468341368e2aa0a115c7dcd37e5229be99, 4cb072453686671f0c094927358cf9944be05e69) intoduced this bug because this revision still works: 5402ef7f70c37b7dff843eb92440fdfee0105469

**Comment by svddries** [comment]
Fixed it. Don't think one of the commits introduced the bug. It was a missing return statement somewhere, so the behavior was quite random. Fixed it, and added -Wall flag to avoid future missing return statements.
