### ISSUE TITLE
Local minimum sergio

### ISSUE THREAD

**Issue by reinzor** [tue-robotics/cb_base_navigation#7]
![screenshotvoorrein](https://cloud.githubusercontent.com/assets/4176023/7031887/1c773626-dd6f-11e4-979b-64c804785df9.png)

**Comment by reinzor** [comment]
![screenshot from 2015-04-07 21 47 18](https://cloud.githubusercontent.com/assets/4176023/7031965/b5d22e70-dd6f-11e4-9e2c-7990bbbe832f.png)

**Comment by Rayman** [comment]
Is this fixed?
